# Generated by Django 2.0.1 on 2018-03-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs', models.PositiveSmallIntegerField()),
                ('views', models.IntegerField()),
                ('status', models.BooleanField()),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
