# Generated by Django 2.2.7 on 2019-12-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='yt_thumbnail',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
