# Generated by Django 2.0.1 on 2018-03-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0002_youtubevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='views',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
