# Generated by Django 2.0.1 on 2018-03-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0004_youtubevideo_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='game_yt_pic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='game_yt_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
