# Generated by Django 2.0.1 on 2018-03-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0005_auto_20180330_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='game',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='game_yt_pic',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='game_yt_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
