# Generated by Django 2.0.1 on 2018-03-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0006_auto_20180330_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='game',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='game_yt_pic',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='game_yt_url',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
