# Generated by Django 2.2 on 2019-07-03 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=20)),
                ('origin_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GttsVoiceLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=10)),
                ('question_text', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.GttsVoiceLanguage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.ChatUser')),
            ],
        ),
    ]
