# Generated by Django 2.2.5 on 2019-09-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='speech_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
