# Generated by Django 2.2.5 on 2019-10-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_remote_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='language',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
