# Generated by Django 2.0.1 on 2018-01-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchstat',
            name='name',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
