# Generated by Django 2.2.7 on 2019-12-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('game', models.CharField(blank=True, max_length=600)),
                ('game_yt_pic', models.CharField(blank=True, max_length=600)),
                ('yt_thumbnail', models.CharField(blank=True, max_length=600)),
                ('game_yt_url', models.CharField(blank=True, max_length=600)),
                ('date', models.DateField(blank=True)),
            ],
        ),
    ]
